### ISSUE TITLE
Removal of `onUnhandledrejection` is a breaking change in latest release

### ISSUE THREAD

**Issue by wozzo** [airbrake/airbrake-js#1385]
# 🐞 bug report

### Affected Package
@airbrake/browser@2.1.9

### Is this a regression?
Yes, the previous version in which this bug was not present was: 2.1.8

### Description
We extended the `Notifier` class and overrode the behaviour of the `onUnhandledrejection` method

## 🔬 Minimal Reproduction

```typescript
import { Notifier, type IOptions } from "@airbrake/browser"

const onerror = window.onerror

class MyNotifier extends Notifier {
	constructor(opt: IOptions) {
  	super(opt)
		window.removeEventListener(
			"unhandledrejection",
			this.onUnhandledrejection
		)
		window.onerror = onerror
  }
  
  protected override onUnhandledrejection(e: any): void {} // error TS4113: This member cannot have an 'override' modifier because it is not declared in the base class 'Notifier'.
}
```

The attempt to override the `onUnhandledrejection` leads to a typescript error since this method has been removed from the base class.

## 🔥 Exception or Error

```typescript
error TS4113: This member cannot have an 'override' modifier because it is not declared in the base class 'Notifier'.
```

## 🌍  Your Environment
**@airbrake/\* version:**
<pre><code>
2.1.9
</code></pre>

**Anything else relevant?**
Introduced by PR https://github.com/airbrake/airbrake-js/pull/1356 as a fix for issue https://github.com/airbrake/airbrake-js/issues/915
