### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.searchParams.append')

### ISSUE THREAD

**Issue by paulvonber** [airbrake/airbrake-js#1000]
# 🐞 bug report

### Affected Package
"@airbrake/browser": "^2.1.3"

### Description
Seems like after upgrading to v2.1.3 strange things appear in error notifier, so shortly error notifier producing errors by itself
Here few screenshots from airbrake panel:
![image](https://user-images.githubusercontent.com/37245111/114895555-e2b2d180-9e0f-11eb-94a7-5a7158ac1acf.png)
![image](https://user-images.githubusercontent.com/37245111/114897337-6c16d380-9e11-11eb-895b-56dd7994092e.png)

Would be nice if it can be fixed as seems like it's crunching quiet a bit of quota everyday :)

**Comment by scottsbaldwin** [comment]
@kyrylo can you please take a look at this?

**Comment by itb2k13** [comment]
Getting this also - I think connected with older browsers not having 'Object.entries' - and then the notifier creates it's own error which creates another error and so forth.

![image](https://user-images.githubusercontent.com/12815952/115018338-9dde7780-9eaf-11eb-86b8-b99e20d2a92b.png)

**Comment by itb2k13** [comment]
Yeah - we also get the 'undefined is not a function' too - same file. v^2.1.3 Not sure if this screener will help track it down:

![image](https://user-images.githubusercontent.com/12815952/115019660-6670ca80-9eb1-11eb-8d02-63293f082d47.png)

**Comment by kyrylo** [comment]
@itb2k13 great find, I think that's exactly the problem here.

**Comment by kyrylo** [comment]
Should be fixed in v2.1.4.
