### ISSUE TITLE
@airbrake/browser apparently imports node types

### ISSUE THREAD

**Issue by pleinonen** [airbrake/airbrake-js#669]
After updating from 1.0.6 to 1.1.0 I saw this compilation error in my Angular app:

error TS2322: Type 'Timeout' is not assignable to type 'number'.
const blurTimeout: number = setTimeout(() => { ... }

In browser correct return type for setTimeout is number so error is not valid. After I reverted back to 1.0.6 problem went away. Timeout is used in Node, could it be that latest version of @airbrake/browser imports Node types?

**Comment by sgray** [comment]
Thanks for the report. I haven't been able to reproduce this issue locally. The steps I've taken:

1. `npm i -g @angular/cli`
1. `ng new test-app`
1. `cd test-app`
1. `npm i @airbrake/browser`
1. 
    ```diff
    diff --git a/src/app/app.component.ts b/src/app/app.component.ts
    index b4efa93..f627174 100644
    --- a/src/app/app.component.ts
    +++ b/src/app/app.component.ts
    @@ -7,4 +7,9 @@ import { Component } from '@angular/core';
     })
     export class AppComponent {
       title = 'test-app';
    +
    +  foo() {
    +    const blurTimeout: number = setTimeout(() => {});
    +    return blurTimeout;
    +  }
     }
    ```
1. `npm run build`
1. Observed no compilation errors



Can you please provide steps to reproduce the issue? Perhaps your app has some different options set in your tsconfig?

**Comment by pleinonen** [comment]
Thank you for taking look at this. While the tsconfig could be the reason, I do not quite understand why problem went away after downgrade back to 1.0.6. 

My project is an Yarn workspace setup and one other project is a Node Express backend, where I am using @airbrake/node version 1.1.0. I do also have multiple tsconfig's and on the root level I do have following type root setting in case that matters (I apparently does not in 1.0.6):

    "typeRoots": [
      "node_modules/@types"
    ],

In your example shouldn't you also import and use Airbrake? I believe Angular AOT & IVY compilation combined with tree shaking should get rid of unused dependencies.

**Comment by sgray** [comment]
>I do not quite understand why problem went away after downgrade back to 1.0.6.

We changed the build setup when we bumped to version 1.1.0, so I think the answer lies somewhere in that change.

I've created https://github.com/sgray/angular-test-app/ and invited you as a collaborator. I followed basically the same steps I described above, and did make sure to import and use Airbrake as you suggested. I still can't recreate the compilation issue you've run into. When you have time, can you please pull that repo and see if you can recreate the issue there? Feel free to push whatever code you want to it.

I _think_ removing [this line](https://github.com/airbrake/airbrake-js/blob/bfcabb4029539f7e30a6456b7e13291a048f59ec/tsconfig.json#L14) will fix your problem, but I can't know for sure until I can reliably reproduce the issue.

**Comment by tempofeng** [comment]
Not exactly the same error, but @airbrake/node includes @airbrake/browser as well.
```
> tsc -b .

node_modules/@airbrake/browser/dist/notifier.d.ts:19:39 - error TS2304: Cannot find name 'PromiseRejectionEvent'.

19     protected onUnhandledrejection(e: PromiseRejectionEvent | CustomEvent): void;
                                         ~~~~~~~~~~~~~~~~~~~~~

node_modules/@airbrake/browser/dist/notifier.d.ts:19:63 - error TS2304: Cannot find name 'CustomEvent'.

19     protected onUnhandledrejection(e: PromiseRejectionEvent | CustomEvent): void;
                                                                 ~~~~~~~~~~~


Found 2 errors.
```

**Comment by sgray** [comment]
@pleinonen friendly ping on this. I also wanted to check if you are excluding `node_modules` in your tsconfig.

**Comment by pleinonen** [comment]
I did take a look at this on your repo and could not reproduce build error. You can kinda see there error though, when hovering over the setTimeout-function and go see the definitions in VS code, you can see that function has been defined in globals.d.ts T(Node) and lib.dom.d.ts (Browser). While I need to figure out why on my project Node is resolved compile time, do you think it's ok to see Node types in browser app? If both @airbrake/browser and @airbrake/node share some code, wouldn't it be better to have that in separate module so both projects would work independently from each other?

**Comment by pleinonen** [comment]
After googling for similar issues I resorted to explicitly use window-version (setTimeout => window.setTimeout) and it seems to work fine.

**Comment by sgray** [comment]
>do you think it's ok to see Node types in browser app?

I see that `@types/node` is included in `devDependencies` by default in a new Angular CLI app, so yes, I do think it's okay. Also, `@types/node` is a dependency of `@angular-devkit/build-angular`, so even if you were to remove `@types/node` from your `package.json`, I think you would still encounter the same issue you're describing.

>If both @airbrake/browser and @airbrake/node share some code, wouldn't it be better to have that in separate module so both projects would work independently from each other?

Yes, definitely. I plan to extract a `core` package that the `browser` and `node` packages can use, but for now, this is what we have.

It sounds like you've found a workaround, so I'm going to close this. As mentioned, I plan to [extract a new package](https://github.com/airbrake/airbrake-js/issues/702), which should remove `@types/node` from being included with `@airbrake/browser`. Perhaps you won't need the workaround once that is completed.
