### ISSUE TITLE
Click on<TypeError: undefined is not a function>

### ISSUE THREAD

**Issue by rinu** [airbrake/airbrake-js#518]
After upgrading to 1.6.3 I see a lot of "Click on`<TypeError: undefined is not a function>`" on airbrake in Occurrence Breadcrumbs. It used to say where the user actually clicked on.

**Comment by vmihailenco** [comment]
Could you show `notice.context`?

**Comment by rinu** [comment]
Modern browsers don't seem to have such issues.

Context for a "Click on`<TypeError: undefined is not a function>`" with someone using Android and Chrome 34:
```
{
  "environment": "production",
  "history": [
    {
      "date": "2019-02-14T07:17:26.016Z",
      "duration": "795",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:17:28.083Z",
      "duration": "204",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:17:30.498Z",
      "num": "2",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    },
    {
      "date": "2019-02-14T07:19:54.643Z",
      "duration": "715",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:20:00.081Z",
      "num": "2",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    },
    {
      "date": "2019-02-14T07:20:03.646Z",
      "duration": "828",
      "method": "POST",
      "statusCode": "200",
      "type": "xhr",
      "url": "https://credy-api.credy.com/v1/sites/25/tc/customers/validate/PL"
    },
    {
      "date": "2019-02-14T07:20:08.253Z",
      "duration": "666",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:20:09.480Z",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    },
    {
      "date": "2019-02-14T07:20:10.937Z",
      "duration": "178",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:20:11.292Z",
      "num": "3",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    },
    {
      "date": "2019-02-14T07:20:17.692Z",
      "duration": "183",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:20:21.413Z",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    },
    {
      "date": "2019-02-14T07:20:26.903Z",
      "duration": "176",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:20:29.093Z",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    },
    {
      "date": "2019-02-14T07:20:31.006Z",
      "duration": "187",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:20:39.345Z",
      "num": "5",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    },
    {
      "date": "2019-02-14T07:21:29.871Z",
      "duration": "667",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:21:32.056Z",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    },
    {
      "date": "2019-02-14T07:21:33.589Z",
      "duration": "176",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-14T07:21:35.595Z",
      "num": "2",
      "target": "<TypeError: undefined is not a function>",
      "type": "click"
    }
  ],
  "language": "JavaScript",
  "messageParams": {
    "func": "undefined"
  },
  "messageRegExp": "(?P<func>.+) is not a function",
  "notifier": {
    "name": "airbrake-js",
    "url": "https://github.com/airbrake/airbrake-js",
    "version": "1.6.3"
  },
  "remoteAddr": "37.248.162.188",
  "remoteCountry": "Poland",
  "remoteCountryCode": "PL",
  "rootDirectory": "https://www.credy.pl",
  "severity": "error",
  "url": "https://www.credy.pl/rejestracja-dlugoterminowa/#forma-zatrudnienia",
  "urlInfo": {
    "fragment": "forma-zatrudnienia",
    "host": "www.credy.pl",
    "path": "/rejestracja-dlugoterminowa/",
    "query": {},
    "scheme": "https"
  },
  "usedSourceMaps": {
    "https://www.credy.pl/_nuxt/5bd7ad6fb1fd63726a52.js": "https://www.credy.pl/_nuxt/5bd7ad6fb1fd63726a52.js.map",
    "https://www.credy.pl/_nuxt/c142eb044104d08d761b.js": "https://www.credy.pl/_nuxt/c142eb044104d08d761b.js.map"
  },
  "userAgent": "Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-N9005 Build/LRX21V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36",
  "userAgentInfo": {
    "browserName": "Android",
    "browserVersion": "2.1",
    "engineName": "AppleWebKit",
    "engineVersion": "537.36",
    "isBot": false,
    "isMobile": true,
    "os": "Android 5.0",
    "platform": "Linux"
  }
}
```

I also found "Click on`<TypeError: Object doesn't support property or method 'from'>`" with IE11.
Full content:
```
{
  "environment": "production",
  "history": [
    {
      "date": "2019-02-15T10:53:55.349Z",
      "duration": "799",
      "method": "POST",
      "statusCode": "200",
      "type": "xhr",
      "url": "https://in.hotjar.com/api/v1/client/sites/1059375/visit-data?sv=5"
    },
    {
      "date": "2019-02-15T10:53:56.668Z",
      "num": "3",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:53:58.647Z",
      "num": "35",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "keypress"
    },
    {
      "date": "2019-02-15T10:54:13.019Z",
      "num": "8",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:55:14.979Z",
      "num": "2",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "keypress"
    },
    {
      "date": "2019-02-15T10:55:17.351Z",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:55:19.741Z",
      "num": "20",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "keypress"
    },
    {
      "date": "2019-02-15T10:55:28.490Z",
      "num": "5",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:55:40.284Z",
      "num": "15",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "keypress"
    },
    {
      "date": "2019-02-15T10:55:44.805Z",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:55:45.498Z",
      "num": "17",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "keypress"
    },
    {
      "date": "2019-02-15T10:55:56.054Z",
      "num": "3",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:56:03.277Z",
      "num": "4",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "keypress"
    },
    {
      "date": "2019-02-15T10:56:04.429Z",
      "num": "3",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:56:08.101Z",
      "num": "4",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "keypress"
    },
    {
      "date": "2019-02-15T10:56:09.652Z",
      "num": "3",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:56:20.602Z",
      "num": "58",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "keypress"
    },
    {
      "date": "2019-02-15T10:56:39.650Z",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    },
    {
      "date": "2019-02-15T10:56:39.533Z",
      "duration": "1375",
      "method": "POST",
      "statusCode": "201",
      "type": "xhr",
      "url": "https://api.airbrake.io/api/v3/projects/200195/notices?key=ac59f8b1a3700c1e6ebf3f890b902dda"
    },
    {
      "date": "2019-02-15T10:56:41.045Z",
      "num": "4",
      "target": "<TypeError: Object doesn't support property or method 'from'>",
      "type": "click"
    }
  ],
  "language": "JavaScript",
  "messageParams": {
    "0": "isNaN"
  },
  "messagePattern": "Object doesn't support property or method {}",
  "notifier": {
    "name": "airbrake-js",
    "url": "https://github.com/airbrake/airbrake-js",
    "version": "1.6.3"
  },
  "remoteAddr": "81.31.24.177",
  "remoteCountry": "United Kingdom",
  "remoteCountryCode": "GB",
  "rootDirectory": "https://www.credy.pl",
  "severity": "error",
  "url": "https://www.credy.pl/rejestracja-jeden-krok/#informacje",
  "urlInfo": {
    "fragment": "informacje",
    "host": "www.credy.pl",
    "path": "/rejestracja-jeden-krok/",
    "query": {},
    "scheme": "https"
  },
  "usedSourceMaps": {
    "https://www.credy.pl/_nuxt/96c6ed764a8ad0f45c6b.js": "https://www.credy.pl/_nuxt/96c6ed764a8ad0f45c6b.js.map",
    "https://www.credy.pl/_nuxt/a44f7579f010c4a78b10.js": "https://www.credy.pl/_nuxt/a44f7579f010c4a78b10.js.map"
  },
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko",
  "userAgentInfo": {
    "browserName": "Internet Explorer",
    "browserVersion": "11.0",
    "engineName": "Trident",
    "engineVersion": "",
    "isBot": false,
    "isMobile": false,
    "os": "Windows 7",
    "platform": "Windows"
  }
}
```

**Comment by vmihailenco** [comment]
Thanks, let's try https://github.com/airbrake/airbrake-js/pull/519
